# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  # install hadolint job
  lint-dockerfile:
    # use docker executor
    docker:
      # Specify the docker image to use for the primary container
      - image: hadolint/hadolint:latest-alpine
    # Specify the steps to run
    steps:
      # checkout the code
      - checkout
      # run hadolint
      - run:
          name: Run Dockerfile
          command: hadolint Dockerfile
  
  # build job
  build-app-karsajobs:
    # use machine executor
    machine:
      # Specify the machine image to use for the primary container
      image: ubuntu-2004:current
      # docker layer caching set to true for faster builds
      docker_layer_caching: true
    # Specify the steps to run
    steps:
      # checkout the code
      - checkout
      # run build and push docker image
      - run:
          name: Build and push Docker image
          command: sh build_push_image_karsajobs_ui.sh

# Invoke jobs via workflows.
workflows:
  ci-frontend-workflow:
    jobs:
      # run lint dockerfile job
      - lint-dockerfile:
          # filter the branch only for karsajobs ui
          filters:
            branches:
              only:
                - karsajobs-ui
      # run build job
      - build-app-karsajobs:
          # require lint dockerfile job to be success
          requires:
            - lint-dockerfile
          # filter the branch only for karsajobs ui
          filters:
            branches:
              only:
                - karsajobs-ui